board/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index,name='login'),
    path('daily_connect/', views.afterlogin, name='daily_connect'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('create/', views.create.as_view(), name='create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from board import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

board/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class userAccount(models.Model):
    uaerId = models.CharField(max_length=30)
    userPassword = models.CharField(max_length=50)
    name = models.CharField(max_length=10)
    birthday = models.CharField(max_length=8)
    gender = models.CharField(max_length=2)
    address = models.TextField()
    phoneNumber = models.CharField(max_length=11)

board/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

from .models import Board
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login

def index(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return afterlogin(request)
        else:
            return render(request, 'board/board_login.html', {'error_message': '아이디 혹은 비밀번호가 잘못되었습니다.'})
    return render(request, 'board/board_login.html')

def detail(request, board_id):
    board = Board.objects.get(id=board_id)
    context = {'board' : board}
    return render(request, 'board/board_detail.html', context)

def afterlogin(request):
   board_list = Board.objects.order_by('create_date')
   context = {'board_list': board_list}
   return render(request, 'board/board_list.html',context)

class create(generic.CreateView):
    model = Board
    fields = ['subject', 'content', 'create_date']
    success_url = reverse_lazy(afterlogin)
    template_name_suffix = '_create'

    

board/templates/board/board_create.html
<form method="post">
  {% csrf_token %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Connect</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
    }

    form {
      max-width: 600px;
      width: 100%;
      padding: 20px;
      background-color: #ffffff;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    label {
      display: block;
      margin-bottom: 8px;
    }

    input[type="text"],
    textarea {
      width: 100%;
      padding: 10px;
      margin-bottom: 16px;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-sizing: border-box;
    }

    textarea {
      resize: vertical;
      min-height: 150px;
    }

    input[type="submit"] {
      background-color: #FFB6C1;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }

    input[type="submit"]:hover {
      background-color: #004d00;
    }

    header {
      background-color: #ffffff;
      color: #006400;
      text-align: center;
      padding: 20px 0;
    }

    a {
      color: #006400;
      text-decoration: none;
    }
  </style>
</head>

<body>
  <header>
    <h1><a href="{% url 'daily_connect' %}" style="text-decoration: none; color: #006400;">Daily Connect</a></h1>
  </header>

  <form action="board/board_list.html" method="post">
    

    <div>
      <label for="id_subject">제목:</label>
      <input type="text" name="subject" maxlength="200" required id="id_subject">
    </div>

    <div>
      <label for="id_content">내용:</label>
      <textarea name="content" cols="50" rows="10" required id="id_content"></textarea>
    </div>

    <div>
      <label for="id_create_date">작성일:</label>
      <input type="text" name="create_date" required id="id_create_date">
    </div>

    <input type="submit" value="등록">
  </form>
</body>

</html>

</form>

board/templates/board/board_detail.html
 <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    header {
      background-color: #f4f4f4;
      color: #006400;
      text-align: center;
      padding: 20px 0;
    }
  </style>
  <title>Daily Connect</title>
  <header>
    <h1><a href="{% url 'daily_connect' %}" style="text-decoration: none; color: #006400;">Daily Connect</a></h1>
  </header>
    <div style="
        text-align: center; margin-top: 0px; margin-left: 250px; margin-right: 250px;
        border: 1px solid black;
        border-radius: 50px; 
        background-color: #FFE6E6;
        padding: 0px;">
        <h2>{{ board.subject }}</h2></div>
    <div style="
        text-align: center;
        margin-top: 0px;
        margin-left: 250px; 
        margin-right: 250px;
        border: 1px dashed black;
        border-radius: 14px;
        margin-top: 10px;
        padding: 40px;">
        {{ board.content }}
    </div>
<div style="position: absolute; right: 20px; bottom: 15px;">
    <strong>작성일시 :</strong> {{ board.create_date}}
</div>

board/templates/board/board_list.html
{% if board_list %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Connect</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    header {
      background-color: #f4f4f4;
      color: #006400;
      text-align: center;
      padding: 20px 0;
    }

    header a.button {
      background-color: #FFB6C1;
      color: #ffffff;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
    }

    a {
      color: #006400;
      text-decoration: none;
    }

    .container {
      max-width: 800px;
      margin: 0 auto;
    }

    .table-container {
      border-radius: 10px; /* 테이블의 겉 테두리만 둥글게 만듦 */
      overflow: hidden;
      margin-top: 20px;
    }

    table {
      border-collapse: collapse;
      width: 100%;
      background-color: #ffffff;
    }

    th, td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 12px;
      max-width: 200px;
    }

    td {
      white-space: nowrap;
      text-overflow: ellipsis;
      overflow: hidden;
    }

    th {
      background-color: #FFB6C1;
      color: #ffffff;
    }

    .no-data {
      text-align: center;
      margin-top: 50px;
    }
  </style>
</head>
<body>
  <header>
    <h1><a href="{% url 'daily_connect' %}" style="text-decoration: none; color: #006400;">Daily Connect</a></h1>
    <a href="{% url 'create' %}" class="button">글쓰기</a>
  </header>
  <div class="container">
    {% if board_list %}
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>No</th>
              <th>제목</th>
              <th>미리보기</th>
              <th>게시일</th>
            </tr>
          </thead>
          <tbody>
            {% for board in board_list %}
              <tr>
                <td>{{ board.id }}</td>
                <td><strong><a href="/board/{{ board.id }}/">{{board.subject}}</a></strong></td>
                <td><strong><a href="/board/{{ board.id }}/">{{board.content}}</a></strong></td>
                <td><strong><a href="/board/{{ board.id }}/">{{board.create_date}}</a></strong></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="no-data">
        <p>현재 게시물이 없습니다...</p>
      </div>
    {% endif %}
  </div>
</body>

</html>
{% endif %}

board/templates/board/board_login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Connect</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      height: 100vh;
    }

    .login-container {
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      padding: 20px;
      width: 300px;
      text-align: center;
    }

    input {
      width: 100%;
      padding: 10px;
      margin: 10px 0;
      box-sizing: border-box;
    }

    button {
      width: 100%;
      padding: 10px;
      background-color: #4caf50;
      color: #fff;
      border: none;
      border-radius: 3px;
      cursor: pointer;
    }

    .logo {
      text-align: center;
      margin-top: 50px;
      margin-bottom: 50px;
    }

    .logo a {
      text-decoration: none;
      font-size: 30px;
      color: #006400;
      font-weight: bold;
    }
  </style>
</head>
<body>

<div class="logo">
  <a href="/board">Daily Connect</a>
</div>

<div class="login-container">
    <h2>Login</h2>
    <form method="post" action="{% url 'login' %}">
      {% csrf_token %}
      <label for="username"><strong>Username</strong></label>
      <input type="text" id="username" name="username" required>
  
      <label for="password"><strong>Password</strong></label>
      <input type="password" id="password" name="password" required>
  
      <button type="submit">Login</button>
    </form>
  </div>

<script>
  function login() {
    var username = document.getElementById("username").value;
    var password = document.getElementById("password").value;
    console.log("Username: " + username);
    console.log("Password: " + password);
    window.location.href = "/board_list/";
  }
</script>
</body>
</html>